// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuBy-Bh8iNFUl81DcTuhndP_8_mbTXCJg',
    appId: '1:1003455371096:android:82c4af94eb172e0c77772d',
    messagingSenderId: '1003455371096',
    projectId: 'defectreporter-f8615',
    storageBucket: 'defectreporter-f8615.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8pzz4b1N2ObFvwHtpgiwrcXWly1o_hl8',
    appId: '1:1003455371096:ios:c35f562a1578cf8077772d',
    messagingSenderId: '1003455371096',
    projectId: 'defectreporter-f8615',
    storageBucket: 'defectreporter-f8615.firebasestorage.app',
    iosBundleId: 'com.example.defectReporter',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYugQn2CW_D2zj1GXXuY7Rim5JniuFXa4',
    appId: '1:1003455371096:web:c117fe91fddb0b9e77772d',
    messagingSenderId: '1003455371096',
    projectId: 'defectreporter-f8615',
    authDomain: 'defectreporter-f8615.firebaseapp.com',
    storageBucket: 'defectreporter-f8615.firebasestorage.app',
  );

}